### ISSUE TITLE
OBS 30.2.0 compatibility

### ISSUE THREAD

**Issue by kaymyst** [miaulightouch/obs-virtual-cam#24]
Hi I'm not sure if you are getting the same issue after upgrading OBS to 30.2:

12:00:31.072: LoadLibrary failed for '../../obs-plugins/64bit/obs-virtualcam.dll': The specified module could not be found.
12:00:31.072:  (126)
12:00:31.072: Module '../../obs-plugins/64bit/obs-virtualcam.dll' not loaded

thanks for a great tool

**Comment by MaikTheGray** [comment]
Yeah, I'm having problems as well, I didn't get any message, but the filter VirtualCam cannot be added any more to my sources, and the ones that were already there cannot be used, since when I click on them they show the message: "No properties avaiable"

**Comment by billy-sung** [comment]
yes, it's undocumented breaking change from OBS 30.2.0, it would be fixed asap.

**Comment by miaulightouch** [comment]
Did you update to the latest version?

**Comment by MaikTheGray** [comment]
Weel it was working, I updated OBS, stopped working, I updated to the last version, still not working (the previous last version was not working for me already though, I don't know if it is because the OBS I'm installing it in is portable or if it something else)

**Comment by miaulightouch** [comment]
Do you update the plugin?

**Comment by miaulightouch** [comment]
Can you provide the full log?

by the way, it’s not recommended to use the portable version OBS, or you have to register virtual cam manually.

**Comment by MaikTheGray** [comment]
Yeah, I know, is just that I cannot not use the portable version, everything is set like this at the moment, and I can't reverse where to put the VirtualCam, because of the greenscreen, is a whole thing...do you want the log of me just entering OBS? Because I can't use VirtualCam, is that log enough?

**Comment by billy-sung** [comment]
> Yeah, I know, is just that I cannot not use the portable version, everything is set like this at the moment, and I can't reverse where to put the VirtualCam, because of the greenscreen, is a whole thing...do you want the log of me just entering OBS? Because I can't use VirtualCam, is that log enough?

I can get your specifications and running environment from the log to reproduce the issue because I don’t have any issues with OBS 30.2.0.

**Comment by MaikTheGray** [comment]
Here it is: https://obsproject.com/logs/uz2gkrr3nAjPwOKK

**Comment by miaulightouch** [comment]
Okay, I got it. This plugin has a dependency on FFmpeg that is shipped with the OBS installation. In OBS 30.2.0, one of the dependencies, FFmpeg, was updated. Depending on the FFmpeg shipped with OBS is not part of the public API, so it's very easy to cause issues.

I have decided to ship FFmpeg with this plugin alone to prevent further dependency issues, but the distribution will be significantly larger due to the FFmpeg libraries.

I will try to remove the FFmpeg libraries when the next OBS public API breaking change occurs. Until that happens, the FFmpeg library will always be shipped along with this plugin.

**Comment by miaulightouch** [comment]
it's fixed by #25

**Comment by MaikTheGray** [comment]
Just tried, still doesn't work: https://obsproject.com/logs/y7trO3rFZF8pOVXZ

**Comment by phillypro** [comment]
yea im noticing the other release you have 3.1.1 works in obs 30.2  but causes an error on exit of obs
the 2.1.1 doesnt show up in the obs menu at all

**Comment by MaikTheGray** [comment]
I downloaded and installed 2.1.1 on both versions though, first portable and then the main one (both using the windows installer), is weird that they are not apperatin at all...the 3.1.1 was basically the same to me, although it might show in the logs, was changing nothing on the "user" sides of things, didn't appear as a filter, nor in the "Tools" section in the toolbar

**Comment by miaulightouch** [comment]
I found that issue #19 is magically fixed in OBS 30.2.0 with the 2.1.2 release.

**Comment by miaulightouch** [comment]
@kaymyst Does the latest release resolve this issue?

**Comment by kaymyst** [comment]
yes it does thank you so much!
